// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.unspecced.initAgeAssurance

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedInitAgeAssurance_Input is the input argument to a app.bsky.unspecced.initAgeAssurance call.
type UnspeccedInitAgeAssurance_Input struct {
	// email: The user's email address to receive assurance instructions.
	Email string `json:"email" cborgen:"email"`
	// language: The user's preferred language for communication during the assurance process.
	Language string `json:"language" cborgen:"language"`
}

// UnspeccedInitAgeAssurance_Output is the output of a app.bsky.unspecced.initAgeAssurance call.
type UnspeccedInitAgeAssurance_Output struct {
	Success bool `json:"success" cborgen:"success"`
}

// UnspeccedInitAgeAssurance calls the XRPC method "app.bsky.unspecced.initAgeAssurance".
func UnspeccedInitAgeAssurance(ctx context.Context, c util.LexClient, input *UnspeccedInitAgeAssurance_Input) (*UnspeccedInitAgeAssurance_Output, error) {
	var out UnspeccedInitAgeAssurance_Output
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.bsky.unspecced.initAgeAssurance", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
